name: Python package

on: [push, pull_request]

jobs:
  code-quality:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python.
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Create venv
      run: |
           uv venv --no-project --no-config --no-managed-python rpy2-r6-env
    - name: Lint with flake8
      run: |
        source rpy2-r6-env/bin/activate
        uv pip install flake8
        flake8 rpy2_r6 --count --max-complexity=10 --max-line-length=127 --statistics
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, "3.10", "3.11", "3.12", "3.13"]
        r-version: ['release']
        os: [ubuntu-24.04, ubuntu-latest, macOS-14]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Create venv
      run: |
           uv venv --no-project --no-config --no-managed-python rpy2-r6-env
    - name: Set up R ${{ matrix.r-version }}
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}
    - name: Install R dependencies
      run: |
        install.packages("R6")
      shell: Rscript {0}
    - name: Install dependencies
      run: |
        source rpy2-r6-env/bin/activate
        uv pip install rpy2
    - name: Install package
      run: |
        source rpy2-r6-env/bin/activate
        uv pip install .
    - name: Test with pytest
      run: |
        source rpy2-r6-env/bin/activate
        export LD_LIBRARY_PATH=$(python -m rpy2.situation LD_LIBRARY_PATH):${LD_LIBRARY_PATH}
        uv pip install pytest codecov pytest-cov
        pytest --cov rpy2_r6.R6 rpy2_r6/tests*
